const pushBackReason = {
  "CREDIT-STAFF-MEILIJIE-C": [{
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }],
  "CREDIT-STAFF-MEILIJIE-B": [{
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }],
  "CREDIT-STAFF-MEILIJIE-A": [{
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }],
  "H5-Staff-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-Staff-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-Staff-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "YHD-GJJ-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "APP-JDD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-STAFF-APPSHEBAODAI-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "YHD-GJJ-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "APP-JDD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-STAFF-APPSHEBAODAI-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "CREDIT-STAFF-MEILIJIE-D": [{
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }],
  "LOAN-STAFF-APPSHEBAODAI-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-GJJD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-STAFF-FANLIWANG-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-APPSHEBAODAI-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-JDD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "YHD-GJJ-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "APP-JDD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-GJJD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-GJJD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-GJJD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-STAFF-ZIRUDAI-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "LOAN-STAFF-ZIRUDAI-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "LOAN-STAFF-ZIRUDAI-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "CREDIT-STAFF-SCENE-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-ZIRUDAI-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "SHD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "Feidee-Staff-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }],
  "SHD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "Feidee-Staff-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }],
  "SHD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "Feidee-Staff-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }],
  "SHD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "LOAN-STAFF-XSELL-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "LOAN-STAFF-XSELL-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "LOAN-STAFF-XSELL-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "LOAN-STAFF-XSELL-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "GJJ-H5-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "Kaniu-EasyB-Staff-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }],
  "default": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "32",
    "description": "请您补充近三个月的工资卡流水或其他收入证明材料"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "47",
    "description": "您的房产复印件或按揭合同或抵押合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "48",
    "description": "您的营业执照照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "50",
    "description": "您的经营场所租赁合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "52",
    "description": "您的征信授权失败，请重新上传"
  }, {
    "codeId": "53",
    "description": "公积金授权失败"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "55",
    "description": "单位电话长时间无人接听"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "59",
    "description": "请补充单位法人联系方式"
  }, {
    "codeId": "60",
    "description": "您提供的店铺照片不符合要求，请重新拍照上传店铺照片"
  }, {
    "codeId": "61",
    "description": "您的借记卡不符合审核要求，请确保上传的为工资卡并重新授权"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }, {
    "codeId": "67",
    "description": "请补充公司/店铺经营信息"
  }, {
    "codeId": "68",
    "description": "银行卡正面照片"
  }, {
    "codeId": "69",
    "description": "银行卡反面照片"
  }],
  "CREDIT-STAFF-SCENE-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "CREDIT-STAFF-SCENE-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "CREDIT-STAFF-SCENE-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-BUSINESS-WEIXUAN-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-JDDV2-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-BUSINESS-DSD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "LOAN-BUSINESS-WEIXUAN-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-JDDV2-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-BUSINESS-WEIXUAN-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-BUSINESS-DSD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "LOAN-BUSINESS-DSD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "LOAN-BUSINESS-WEIXUAN-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-JDDV2-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-BUSINESS-DSD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "H5-JDDV2-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "Kaniu-EasyB-Staff-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }],
  "Kaniu-EasyB-Staff-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }],
  "H5-DSD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "SDD-WLD-Staff-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "32",
    "description": "请您补充近三个月的工资卡流水或其他收入证明材料"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }],
  "H5-DSD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "SDD-WLD-Staff-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "32",
    "description": "请您补充近三个月的工资卡流水或其他收入证明材料"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }],
  "SDD-WLD-Staff-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "32",
    "description": "请您补充近三个月的工资卡流水或其他收入证明材料"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }],
  "H5-DSD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "SDD-WLD-Staff-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "32",
    "description": "请您补充近三个月的工资卡流水或其他收入证明材料"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }],
  "H5-DSD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "62",
    "description": "店铺网址核验无效，请重新填写"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }],
  "APP-XYKD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-XYKD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-XYKD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "APP-XYKD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }],
  "LOAN-OWNER-HEXINHOUSE-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "47",
    "description": "您的房产复印件或按揭合同或抵押合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "50",
    "description": "您的经营场所租赁合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "52",
    "description": "您的征信授权失败，请重新上传"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "55",
    "description": "单位电话长时间无人接听"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "59",
    "description": "请补充单位法人联系方式"
  }, {
    "codeId": "60",
    "description": "您提供的店铺照片不符合要求，请重新拍照上传店铺照片"
  }, {
    "codeId": "61",
    "description": "您的借记卡不符合审核要求，请确保上传的为工资卡并重新授权"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }, {
    "codeId": "67",
    "description": "请补充公司/店铺经营信息"
  }, {
    "codeId": "68",
    "description": "银行卡正面照片"
  }, {
    "codeId": "69",
    "description": "银行卡反面照片"
  }],
  "LOAN-OWNER-HEXINHOUSE-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "47",
    "description": "您的房产复印件或按揭合同或抵押合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "50",
    "description": "您的经营场所租赁合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "52",
    "description": "您的征信授权失败，请重新上传"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "55",
    "description": "单位电话长时间无人接听"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "59",
    "description": "请补充单位法人联系方式"
  }, {
    "codeId": "60",
    "description": "您提供的店铺照片不符合要求，请重新拍照上传店铺照片"
  }, {
    "codeId": "61",
    "description": "您的借记卡不符合审核要求，请确保上传的为工资卡并重新授权"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }, {
    "codeId": "67",
    "description": "请补充公司/店铺经营信息"
  }, {
    "codeId": "68",
    "description": "银行卡正面照片"
  }, {
    "codeId": "69",
    "description": "银行卡反面照片"
  }],
  "LOAN-OWNER-HEXINHOUSE-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "47",
    "description": "您的房产复印件或按揭合同或抵押合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "50",
    "description": "您的经营场所租赁合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "52",
    "description": "您的征信授权失败，请重新上传"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "55",
    "description": "单位电话长时间无人接听"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "59",
    "description": "请补充单位法人联系方式"
  }, {
    "codeId": "60",
    "description": "您提供的店铺照片不符合要求，请重新拍照上传店铺照片"
  }, {
    "codeId": "61",
    "description": "您的借记卡不符合审核要求，请确保上传的为工资卡并重新授权"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }, {
    "codeId": "67",
    "description": "请补充公司/店铺经营信息"
  }, {
    "codeId": "68",
    "description": "银行卡正面照片"
  }, {
    "codeId": "69",
    "description": "银行卡反面照片"
  }],
  "LOAN-OWNER-HEXINHOUSE-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "47",
    "description": "您的房产复印件或按揭合同或抵押合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "49",
    "description": "您的与客户经理合影照片不够清晰完整，请重新拍照上传"
  }, {
    "codeId": "50",
    "description": "您的经营场所租赁合同照片不完整或者模糊，请对照要求补充拍照上传"
  }, {
    "codeId": "52",
    "description": "您的征信授权失败，请重新上传"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "55",
    "description": "单位电话长时间无人接听"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "59",
    "description": "请补充单位法人联系方式"
  }, {
    "codeId": "60",
    "description": "您提供的店铺照片不符合要求，请重新拍照上传店铺照片"
  }, {
    "codeId": "61",
    "description": "您的借记卡不符合审核要求，请确保上传的为工资卡并重新授权"
  }, {
    "codeId": "63",
    "description": "请补充配偶身份证正面（显示四个边角）"
  }, {
    "codeId": "64",
    "description": "请补充配偶身份证反面（显示四个边角）"
  }, {
    "codeId": "65",
    "description": "请补充配偶手持结婚证拍照"
  }, {
    "codeId": "67",
    "description": "请补充公司/店铺经营信息"
  }, {
    "codeId": "68",
    "description": "银行卡正面照片"
  }, {
    "codeId": "69",
    "description": "银行卡反面照片"
  }],
  "H5-JDDV3-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "H5-JDDV3-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "H5-JDDV3-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "Kaniu-Staff-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }],
  "Kaniu-Staff-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }],
  "Kaniu-Staff-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }],
  "Kaniu-Staff-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }],
  "H5-JDDV3-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "8",
    "description": "请填写父母或者配偶的联系方式"
  }, {
    "codeId": "9",
    "description": "请补充您信用卡最近一个月的还款记录"
  }, {
    "codeId": "10",
    "description": "请补充您贷款最近一个月的还款凭证"
  }, {
    "codeId": "13",
    "description": "请授权支付宝"
  }, {
    "codeId": "16",
    "description": "您的单位信息（单位名称/单位地址）填写有误，请重新填写后提交申请"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "31",
    "description": "您提供的同事联系人不符合要求，请填写现职单位同事的联系方式"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "39",
    "description": "请授权运营商"
  }, {
    "codeId": "54",
    "description": "请授权社保"
  }, {
    "codeId": "57",
    "description": "请授权公积金"
  }, {
    "codeId": "66",
    "description": "请授权工资卡"
  }],
  "LOAN-STAFF-JIEDIANQIAN-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-JIEDIANQIAN-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-JIEDIANQIAN-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-JIEDIANQIAN-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "Kaniu-EasyA-Staff-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }],
  "Kaniu-EasyA-Staff-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }],
  "Kaniu-EasyA-Staff-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }],
  "CREDIT-STAFF-51GJJ-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "CREDIT-STAFF-51GJJ-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-INSTALLMENT-CHEXIAN-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-INSTALLMENT-CHEXIAN-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "CREDIT-STAFF-51GJJ-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-INSTALLMENT-CHEXIAN-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "CREDIT-STAFF-51GJJ-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-INSTALLMENT-CHEXIAN-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "GJJ-APP-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "GJJ-APP-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-Staff-JDD-D": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "GJJ-APP-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "GJJ-APP-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "H5-Staff-JDD-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "H5-Staff-JDD-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "H5-Staff-JDD-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }, {
    "codeId": "43",
    "description": "您提供的营业执照照片不符合要求，请参照提示补充规范的营业执照原件照片"
  }, {
    "codeId": "44",
    "description": "请补充您与店铺门头合影照片"
  }, {
    "codeId": "45",
    "description": "您的运营商授权存在问题，请重新授权运营商"
  }],
  "FOXCONN": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-FANLIWANG-A": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-FANLIWANG-B": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }],
  "LOAN-STAFF-FANLIWANG-C": [{
    "codeId": "5",
    "description": "您的电话多次未能接通，请保持手机畅通后重新提交"
  }, {
    "codeId": "21",
    "description": "请补充清晰完整(显示四个边角）的国徽面身份证照片"
  }, {
    "codeId": "22",
    "description": "请补充清晰完整(显示四个边角）的头像面身份证照片"
  }, {
    "codeId": "23",
    "description": "您的手持身份证照片不符合要求，请重新拍照、上传补充清晰完整五官无遮挡的手持身份证照片"
  }, {
    "codeId": "24",
    "description": "请将您的三方协议拍照上传，需包含本人姓名、学校公章、公司公章、工资相关页面"
  }, {
    "codeId": "25",
    "description": "您提供的工作证明资料不符合要求，请参照提示补充规范的工牌/劳动合同/公司开具的工作证明"
  }, {
    "codeId": "37",
    "description": "请授权常用信用卡"
  }]
}


export default pushBackReason;